version: "3.7"

services:
  php:
    image: try-m/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - codebase:/var/www/html

  crond:
    image: try-m/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - codebase:/var/www/html

  nginx:
    volumes:
    - codebase:/var/www/html

volumes:
  codebase: